### ISSUE TITLE
Serve static files (js, html, css)

### ISSUE THREAD

**Issue by grondinjc** [WINOT/cide.py#2]
This does not include html templates.
This can be done by nginx, cherrypy, or any other usefull tool.

For cherrypy :
http://cherrypy.readthedocs.org/en/latest/basics.html#static-content-serving

**Comment by vphilippon** [comment]
I think PR #13 takes care of this for the WelcomeController and IDEController. Of course, the config for each subsequent controller will need to be set accordingly.

No tests were made or performed for this though. Any idea on how to do unittest for this^
(use curl or something?)

**Comment by vphilippon** [comment]
Ok, we definetely got that covered. Closing.
